### ISSUE TITLE
redirecionar gokoni.com.br para gokoni.com

### ISSUE THREAD

**Issue by paulogeyer** [matthewrudy/memoist#31]
fiz algumas mudanças no Route 53 da Amazon, seguindo esse guia http://www.holovaty.com/writing/aws-domain-redirection/

esperando o DNS atualizar pra ver se funcionou

**Comment by matthewrudy** [comment]
I think this was a mistake.

**Comment by paulogeyer** [comment]
yes, it was a mistake (I have no idea why I wrote this issue here, it is about other project)

**Comment by matthewrudy** [comment]
@paulogeyer no worries ;)
