### ISSUE TITLE
Support reloading a file while in a console

### ISSUE THREAD

**Issue by lardcanoe** [matthewrudy/memoist#32]
If I make a change to a file and want to reload it in my pry session I get AlreadyMemoizedError. It would be great if there was a simple way to call `load '...'` on a file that contains memoize and have it work.

**Comment by matthewrudy** [comment]
That's interesting.

The error exists to avoid users accidentally memoizing twice.

But an alternative would be just to do a `warn("already been memoized")`

I'm OK with that.
I just wonder if anyone out there is relying upon this exception..

I should hope not.

**Comment by lardcanoe** [comment]
I'd be happy with a class method that I can call to remove.

foo.rb:

```
class Foo
  extend Memoist

  def bar
   42
  end
  memoize :bar
end
```

then calling something like `Foo.unmemoize` before `load 'foo.rb'` would be fine. Note that I have to do it on the class, and not on any instances of Foo, which I no longer have access to.

If you can suggest what `unmemoize` would look like I can make it happen.

Thanks!

**Comment by pboling** [comment]
Is there actually any harm in memoizing twice, besides the tiny performance hit?  If it doesn't harm the result, the I think the error is unwarranted.

**Comment by matthewrudy** [comment]
The problem is the aliasing.

It's better to just do nothing than re-memoize.

**Comment by pboling** [comment]
But it could just warn instead of re-aliasing?  If it is raising now because it detects the problem, supposedly we could be not raising and skipping the aliasing, and warning only?

**Comment by matthewrudy** [comment]
Sure @pboling, that's my suggestion.

* Remove the current `raise`
* Issue a `warn` instead.

**Comment by matthewrudy** [comment]
Feel free to implement it and issue a PR.
I don't have a computer at the moment (hopefully it'll be back next week)
