### ISSUE TITLE
Add changelog?

### ISSUE THREAD

**Issue by JacobEvelyn** [matthewrudy/memoist#80]
We like keeping our gems up to date, but when upgrading Memoist it's hard to know what the changes are between gem versions, and especially if there are backwards-incompatible changes between versions. A `CHANGELOG.md` file would be extremely helpful.

**Comment by matthewrudy** [comment]
@JacobEvelyn that's fine
but it hasn't changed or 1.5 years,
and I mostly don't see the point of adding new features.

If anything reasonable changes would probably just to be cut support to anything less than ruby 2.4
as everything else is End Of Life
and see if that cleans anything up.

But mostly I feel like just leaving it,
as it works for most cases the way it always has.

**Comment by matthewrudy** [comment]
added that in https://github.com/matthewrudy/memoist/commit/510cb571cdea0fcb72fa8ec7560bc876f933f442

Thanks @JacobEvelyn

**Comment by JacobEvelyn** [comment]
Thanks so much @matthewrudy!
