### ISSUE TITLE
Name error when calling query methods

### ISSUE THREAD

**Issue by ansarada-dantan** [matthewrudy/memoist#85]
Hi,

Since moving to memoist 0.16.1 we started getting this error:
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/memoist-0.16.1/lib/memoist.rb:140:in `alias_method': undefined method `exists_query' for class `Stacker::Stack' (NameError)

It looks like this line is causing errors:
https://github.com/ansarada/stacker/blob/master/lib/stacker/stack.rb#L29

when memoist is being called here:
https://github.com/ansarada/stacker/blob/master/lib/stacker/stack.rb#L66

I _think_ the trailing "?" is causing issues with the latest version of memosit

**Comment by sebjacobs** [comment]
Sorry about the late response. This should be fixed in (https://github.com/matthewrudy/memoist/commit/72d40af99e955dd5904cfb8edcb0606eb165c4cb).
